name: medbook
description: Offline clinical reference prototype
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.12.0
  flutter: ^3.44.0

dependencies:
  bloc: ^9.2.1
  dio: ^5.9.0
  dot_matrix_loader: ^0.2.0
  drift: ^2.34.4
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.2.0
  get_it: ^8.0.3
  go_router: ^17.3.0
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.12.0

dev_dependencies:
  bloc_lint: ^0.4.1
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.24
  build_runner: ^2.10.5
  drift_dev: 2.34.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.14.1
  mocktail: ^1.0.5
  very_good_analysis: ^10.3.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: InterText
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
          weight: 500
    - family: InterDisplay
      fonts:
        - asset: assets/fonts/inter/Inter_28pt-Bold.ttf
          weight: 700
